### ISSUE TITLE
Using zippa on a complex tree (concrete syntax tree)

### ISSUE THREAD

**Issue by CMCDragonkai** [tommikaikkonen/zippa#1]
Is there a way to make use of zippa on a non-uniform JS tree with both objects and arrays? Basically I'm looking for a way to traverse an arbitrary JS object that has arrays and other properties, and be able to mutate them and work with them using the zipper pattern.

SpecificallyI have a concrete syntax tree produced out of from chevrotain. Here's the example: https://github.com/SAP/chevrotain/blob/master/docs/concrete_syntax_tree.md

So something like this: 

```
{
  name: "grammar rule",
  children: [ TokenObject, anotherCstNode ]
}
```

According to the README, making a zippa requires 3 functions, determining if something is a branch, getting the children, and making a new node.

However in my case, I may want to make a specific kind of token object, a complete cst node with a certain name... etc. These are all different.

**Comment by tommikaikkonen** [comment]
You are correct, `zippa` interfaces with your data only through the three functions provided. From looking at the CST data, you may be able to operate on it with a zipper, though I'm not familiar enough with the chevrotain, its CST and the problem domain to say if it is practical or the best approach. Anyway, I'll give it a shot.

I see that the CST data often uses objects as children, where the value on each property has a distinct semantic meaning based on the key:

```js
{
  name: "qualifiedName",  
  children: {
      Dot : ["."],
      Identifier : ["foo", "bar"]
  }
}
```

I'm referring to the `Dot` and `Identifier` keys above. If we consider the above data as a node in a tree, and we want to consider `['.']` and `['foo', 'bar']` as its children, we have a problem. Reconstructing `Identifier: ['foo', 'bar']` from only `['foo', 'bar']` is not possible—it could be something else than `Identifier` for all we know. Writing `makeNode` would not be possible.

My initial thought would be to treat these kinds of objects as a list of associations (of type `Array<[String, Any]>` in TypeScript notation), where you treat each association `[String, Any]` as a (child) node. You would then write the three functions so that they handle both nodes of type `{ name: String, children: Object }` and `[String, Any]`. Without handling any of the edge cases, the basic pattern looks like this:

```js
import {
    fromPairs,
    toPairs,
} from 'ramda';

function getChildren(node) {
    if (node instanceof Array && node.length === 2) {
        // What you want to do here depends on the problem domain.
        // (Maybe these are always leaves in the tree)?
        const [name, children] = node;
        return children;
    }
    return toPairs(node.children);
}
function makeNode(oldParent, children) {
    if (oldParent instanceof Array && oldParent.length === 2) {
        const [oldName, _oldChildren] = oldParent;
        return [oldName, children];
    }
    return {
        name: oldParent.name,
        // Note that your application should enforce that all the children
        // here are of type [String, Any]
        children: fromPairs(children),
    };
}

function isBranch(node) {
    // TODO
}
```

These should set up the zipper structure for operating on the CST. In your tree operations you need to know when to return nodes of type `[String, Any]` and `{ name: String: children: Object }`.

**Comment by CMCDragonkai** [comment]
I realised that the cst is not very good due to lack of ordering between subrules. So I'm building my own CST now, this issue shouldn't be a problem.

**Comment by CMCDragonkai** [comment]
Another issue I discovered, is that I actually want to mutate a single CST. So that way zipper cursors all operate on all the same tree. But I don't think this kind of concurrent/mutable zipper pattern has been well investigated. Currently zipper libraries all produce a new tree at the end of the day, and there's no discussion of multiple cursors on the same tree.

**Comment by tommikaikkonen** [comment]
If you want to mutate a tree in-place, the zipper data structure is not the right choice. The zipper data structure originated from needing a functional, immutable, but still fairly performant approach to modifying trees—see [this paper](http://gallium.inria.fr/~huet/PUBLIC/zip.pdf). Instead you can use the tree visitor pattern that far predates zippers, and you should find plenty of information and real world examples on that on the internet.

**Comment by CMCDragonkai** [comment]
I don't know if this is relevant https://pavpanchekha.com/blog/zippers/multi-zippers.html but I'll take a look in the future.
